---
- hosts: my-fw
  connection: local
  gather_facts: false
  vars_files:
    - vars.yml
  roles:
    - PaloAltoNetworks.paloaltonetworks
  tasks:
      - name: Grab auth creds
      include_vars: 'fw_creds.yml'
      no_log: 'yes'

      - name: Add interface management profile
      panos_management_profile:
        provider: '{{ provider }}'
        name: 'allow ssh'
        ssh: true
        commit: false

    - name: add Allow ping
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: Allow ping
        application: ['ping']
        service: ['application-default']
        action: 'allow'
        commit: false

    - name: Configure eth1/1 and put it in zone L3-in
      panos_interface:
        provider: '{{ provider }}'
        if_name: 'ethernet1/1'
        zone_name: 'L3-in'
        commit: false
    - name: commit
      panos_commit:
        provider: '{{ provider }}'

     # permit ssh to 1.1.1.1
    - name: permit ssh to 1.1.1.1
      panos_security_rule:
        ip_address: "{{ mgmt_ip }}"
        password: "{{admin_password}}"
        rule_name: 'SSH permit'
        description: 'SSH rule test'
        source_zone: ['untrust']
        destination_zone: ['trust']
        source_ip: ['any']
        source_user: ['any']
        destination_ip: ['1.1.1.1']
        category: ['any']
        application: ['ssh']
        service: ['application-default']
        hip_profiles: ['any']
        action: 'allow'
        operation: 'add'
        commit: false
